### ISSUE TITLE
Remove data.table dependency?

### ISSUE THREAD

**Issue by lcolladotor** [ComunidadBioInfo/regutools#14]
As far as I can tell, `regutools` only uses one `data.table` function in the whole package at `get_summary()` https://github.com/ComunidadBioInfo/regutools/blob/master/R/get_summary.R. That is the function `melt()`. Maybe we can remove this dependency. Although I guess that `data.table` isn't too bad in terms of dependencies itself https://cran.r-project.org/web/packages/data.table/index.html.

**Comment by lcolladotor** [comment]
Just double checked, and this is still the case.

Onve `get_regulatory_summary()` stops needing `data.table::melt()` then we need to update the DESCRIPTION and vignette. The NAMESPACE should get updated by running `devtools::document()`.

**Comment by jemilianosf** [comment]
I removed the data.table dependency from the function and from the NAMESPACE.
