### ISSUE TITLE
Complete authors and their affiliations

### ISSUE THREAD

**Issue by lcolladotor** [ComunidadBioInfo/regutools#15]
Involves double checking the DESCRIPTION file https://github.com/ComunidadBioInfo/regutools/blob/master/DESCRIPTION and at the beginning of the vignette https://github.com/ComunidadBioInfo/regutools/blob/master/vignettes/regutools.Rmd#L3. Note that some functions list other authors too.

Also double check spelling and accents in all names.

**Comment by lcolladotor** [comment]
Check that all accents are ok in the DESCRIPTION, `inst/CITATION` and vignette files. This applies to all of us!

**Comment by jemilianosf** [comment]
Checked mine.

**Comment by Helysalgado** [comment]
revisado.

**Comment by CarBarJon** [comment]
Checado
