### ISSUE TITLE
Resolve warnings in GRanges_convert tests

### ISSUE THREAD

**Issue by lcolladotor** [ComunidadBioInfo/regutools#16]
Based on:

```
✓ |  16   5   | GRanges_convert [7.2 s]
─────────────────────────────────────────────────────────────────────────────────────
test_convert_granges.R:24: warning: Results from regulondb queries can be converted to GRanges
Dropped 19 entries where genomic coordinates were NAs

test_convert_granges.R:24: warning: Results from regulondb queries can be converted to GRanges
Dropped 19 entries where genomic coordinates were NAs

test_convert_granges.R:27: warning: Results from regulondb queries can be converted to GRanges
Dropped 7 entries where genomic coordinates were NAs

test_convert_granges.R:71: warning: Results from regulondb queries can be converted to Biostrings
Dropped 92 entries where sequence data were NAs

test_convert_granges.R:73: warning: Results from regulondb queries can be converted to Biostrings
Dropped 92 entries where sequence data were NAs
─────────────────────────────────────────────────────────────────────────────────────
```

**Comment by areyesq89** [comment]
This behavior is expected, whenever the regulondb sqlite contains genomic coordinates with NAs and the results are converted from a regulondb_result object to a GRanges object, these are dropped (and a warning is given) since a GRanges object can't have NA values. Any thoughts?

**Comment by lcolladotor** [comment]
Maybe use `expect_warning( call, warningMessage )`? (I think that's the syntax) where the warning message explicitly tests the exact number of expected NAs. Then use `suppressWarnings()` for the tests where you are not testing a specific number of lines dropped but some other functionality.

Something like that

**Comment by areyesq89** [comment]
Good idea! I've incorporated these changes in commit.https://github.com/ComunidadBioInfo/regutools/commit/74859926cb1912bb75d6370e4915ca15ac26ff1b
