### ISSUE TITLE
Change list <- (); for() to lapply()

### ISSUE THREAD

**Issue by lcolladotor** [ComunidadBioInfo/regutools#20]
Avoid defining a list then filling it on a for loop. Instead use lapply()

**Comment by lcolladotor** [comment]
This happens inside `plot_GRanges()` and `get_gene_regulators()`

**Comment by josschavezf** [comment]
change made for plot_GRanges, now called plot_dna_objects

**Comment by jemilianosf** [comment]
I changed the get_gene_regulators one so I'm closing this issue.
