### ISSUE TITLE
List your official publication names

### ISSUE THREAD

**Issue by lcolladotor** [ComunidadBioInfo/regutools#21]
For me it's:

* First name: Leonardo
* Last name: Collado-Torres

**Comment by lcolladotor** [comment]
We'll need this for the paper/pre-print (not the actual package)

**Comment by areyesq89** [comment]
Los míos:
    First name: Alejandro
    Last name: Reyes

**Comment by josschavezf** [comment]
El mío es:
First name: Joselyn
Last name: Chávez

**Comment by CarBarJon** [comment]
First name: Carmina 
Last name: Barberena-Jonas

**Comment by jemilianosf** [comment]
First name: Jesus Emiliano
Last name: Sotelo-Fonseca

**Comment by areyesq89** [comment]
Closing this as we've collected all publication names.
