### ISSUE TITLE
Extend `get_dna_objects()` to accept a GRanges as input

### ISSUE THREAD

**Issue by areyesq89** [ComunidadBioInfo/regutools#28]
It is not high priority, but it would be nice if this function retreives all DNA objects present within a GRanges object.

**Comment by josschavezf** [comment]
@areyesq89 I am a little confused with this issue, the ask is to take a GRanges as input or to output a GRanges? If second option, the function already does that. If you run this example the output is a GRanges object. 
#' if(!exists('regulondb_conn')) regulondb_conn <- connect_database()
#'
#' ## Build the regulondb object
#' e_coli_regulondb <-
#'     regulondb(
#'         database_conn = regulondb_conn,
#'         organism = "chr",
#'         database_version = "1",
#'         genome_version = "1"
#'     )
#'
#' ## Get all genes from E. coli
#' get_dna_objects(e_coli_regulondb)
#'
#' ## Get genes providing Genomic Ranges
#' get_dna_objects(e_coli_regulondb, from = 5000, to = 10000)

**Comment by areyesq89** [comment]
It would be the first option. Something like:

```
get_dna_objects( e_coli_regulondb, grange = GRanges("chr", IRanges(1, 5000) ) )
```

**Comment by josschavezf** [comment]
done
