### ISSUE TITLE
WARNING: Add non-empty \value sections to the man pages

### ISSUE THREAD

**Issue by areyesq89** [ComunidadBioInfo/regutools#32]
WARNING: Add non-empty \value sections to the following man
      pages: man/convert_to_biostrings.Rd, man/convert_to_granges.Rd,
      man/get_gene_regulators.Rd, man/get_gene_synonyms.Rd,
      man/get_regulatory_network.Rd, man/guess_id.Rd,
      man/list_datasets.Rd, man/regulondb-methods.Rd, man/regulondb.Rd

**Comment by CarBarJon** [comment]
Add  \value sections to the following man pages: 
- [x] man/convert_to_biostrings.Rd
- [x] man/convert_to_granges.Rd,
- [ ] man/get_gene_regulators.Rd,
- [ ] man/get_gene_synonyms.Rd,
- [ ] man/get_regulatory_network.Rd, 
- [x] man/guess_id.Rd,
- [x] man/list_datasets.Rd, 
- [ ] man/regulondb-methods.Rd, 
- [ ] man/regulondb.Rd

I will continue tomorrow, But these are the ones that I already did

**Comment by lcolladotor** [comment]
I believe that this has been done already. If I'm mistaken, feel free to re-open the issue.
