### ISSUE TITLE
Document S4 methods

### ISSUE THREAD

**Issue by lcolladotor** [ComunidadBioInfo/regutools#6]
Based on https://travis-ci.org/ComunidadBioInfo/regutools/builds/638199267?utm_medium=notification&utm_source=slack

```R
* checking for missing documentation entries ... WARNING
Undocumented S4 methods:
  generic 'show' and siglist 'regulondb'
```

**Comment by areyesq89** [comment]
Fixed in commit https://github.com/ComunidadBioInfo/regutools/commit/395c14c3c71723b1710ee908710c48eed70ceca3
