### ISSUE TITLE
Document regulondb in list_atributes

### ISSUE THREAD

**Issue by lcolladotor** [ComunidadBioInfo/regutools#7]
Based on https://travis-ci.org/ComunidadBioInfo/regutools/builds/638199267?utm_medium=notification&utm_source=slack

```R
Undocumented arguments in documentation object 'list_attributes'
  ‘regulondb’
```

**Comment by areyesq89** [comment]
Fixed in https://github.com/ComunidadBioInfo/regutools/commit/395c14c3c71723b1710ee908710c48eed70ceca3
